name: Message
on: [push]

jobs:
  build:
    name: Send Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Send Message
        uses: ./.github/workflows/main.workflow
        id: flow
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.flow.outputs.time }}.'
