name: Notification on push
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Slack notification
      env:
        SLACK_WEBHOOK: ${{ secrets.slack_secret }}
      uses: DaleOCoileain/ShopifyWelcome@master
      with:
        args: 'A new commit has been pushed to DaleOCoileain/ShopifyWelcome.'
